# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Duex < Formula
  desc "Duex is a Go-based terminal utility for visualizing and analyzing disk usage, featuring interactive navigation, accurate sizing, and real-time feedback."
  homepage "https://github.com/evilmarty/duex"
  version "1.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/evilmarty/duex/releases/download/v1.3.0/duex-1.3.0-darwin_amd64"
      sha256 "d10e8faa37fedce569fa0aad28faa7a2577a1a6b21e578360ef5cc1546182c53"

      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/evilmarty/duex/releases/download/v1.3.0/duex-1.3.0-darwin_arm64"
      sha256 "4afd94fc78f574af12b6f96692a604acd751399231af4dce78dd4a1260859025"

      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/duex/releases/download/v1.3.0/duex-1.3.0-linux_amd64"
      sha256 "2bf919ec098528c93274a7159d80612a7e9f9b05570c9a13636e29b7019336f3"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/duex/releases/download/v1.3.0/duex-1.3.0-linux_armv6"
      sha256 "d269e22150bbaf2af36100a6e8e1edd6979564a6fd936c15661a4692eed7dd2b"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/duex/releases/download/v1.3.0/duex-1.3.0-linux_arm64"
      sha256 "4133208ba8adb67e913111da7043c59451abb0f40beb8e9e1e5b8d821bb12b1b"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
  end

  head do
    url "https://github.com/evilmarty/duex.git", branch: "main"
    depends_on "go" => :build
  end

  test do
    version_output = shell_output(bin/"duex --version")
    assert_match "duex version #{version}", version_output
  end
end
