# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ilc < Formula
  desc "Simplify creating command-line utilities"
  homepage "https://github.com/evilmarty/ilc"
  version "1.2.0"
  license "GPL"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/evilmarty/ilc/releases/download/v1.2.0/ilc-1.2.0-darwin_amd64"
      sha256 "d0edb4ec713ed306d6163c6492ed894a85bb535cb817bcfa28c67b410670f6fc"

      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/evilmarty/ilc/releases/download/v1.2.0/ilc-1.2.0-darwin_arm64"
      sha256 "dfa0dd956e7fb05b175fb00a31aeb2a89009d91d2de05cc198d05ad69c5a97a6"

      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/ilc/releases/download/v1.2.0/ilc-1.2.0-linux_amd64"
      sha256 "21251c792232264b5d9aa1e7361d996c7a2f8659c5429db96847e75929586f19"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/ilc/releases/download/v1.2.0/ilc-1.2.0-linux_armv6"
      sha256 "e7fd8993d20063cc3ee3fa98b51c3345b9e2a63a2fc4b1c8949343581c1f9750"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/ilc/releases/download/v1.2.0/ilc-1.2.0-linux_arm64"
      sha256 "9997f0722e8d595eef519989f8f860f4885f7aa8cf0933d742b04fecd44ed1fe"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
  end

  head do
    url "https://github.com/evilmarty/ilc.git", branch: "main"
    depends_on "go" => :build
  end

  test do
    version_output = shell_output(bin/"ilc -version")
    assert_match "Version: #{version}", version_output
  end
end
