# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazycommit < Formula
  desc "Automates generating a commit message from staged changes in a Git repository using a pluggable LLM provider"
  homepage "https://github.com/evilmarty/lazycommit"
  version "0.3.0"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/evilmarty/lazycommit/releases/download/v0.3.0/lazycommit-0.3.0-darwin_amd64"
      sha256 "d3fcbf83a702146535ed6819f854a9ea3089b65c6191c547e0e76c1c239b7196"

      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/evilmarty/lazycommit/releases/download/v0.3.0/lazycommit-0.3.0-darwin_arm64"
      sha256 "812ba05bab5df07397a7f61ab526c7108c8757647a44d46ff88f98e5f36c4658"

      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/lazycommit/releases/download/v0.3.0/lazycommit-0.3.0-linux_amd64"
      sha256 "0cfd3d41a889efac5f4d09d0aa15ec9ed6697048b9f6379b5a2a8c617cd99063"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/lazycommit/releases/download/v0.3.0/lazycommit-0.3.0-linux_armv6"
      sha256 "5c7c37ab3a9304f263e9963c98e5fff14eea260448b230824ad07088f4387cab"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/lazycommit/releases/download/v0.3.0/lazycommit-0.3.0-linux_arm64"
      sha256 "befb2d3111286e37fde026a4df604003666d2e7db6fd2864b9aa77ab3562f703"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
  end

  head do
    url "https://github.com/evilmarty/lazycommit.git", branch: "main"
    depends_on "go" => :build
  end

  test do
    version_output = shell_output(bin/"lazycommit --version")
    assert_match "lazycommit version #{version}", version_output
  end
end
