# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazycommit < Formula
  desc "Automates generating a commit message from staged changes in a Git repository using a pluggable LLM provider"
  homepage "https://github.com/evilmarty/lazycommit"
  version "0.1.0-alpha"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/evilmarty/lazycommit/releases/download/v0.1.0-alpha/lazycommit-0.1.0-alpha-darwin_amd64"
      sha256 "a0d42ab5fedc5eed3ca2558e20b1455c530c9d77638fd33a2d001f6bdd1650c4"

      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/evilmarty/lazycommit/releases/download/v0.1.0-alpha/lazycommit-0.1.0-alpha-darwin_arm64"
      sha256 "9c8e67c134796bbf8ea49b4d337aebc639f19ee3b0f09692acfac49ce4555cf2"

      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/lazycommit/releases/download/v0.1.0-alpha/lazycommit-0.1.0-alpha-linux_amd64"
      sha256 "d68f1a8705bc41dfb2dc09ff71e057196d082f6e94d86d8824ed788d19b8d3c4"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/lazycommit/releases/download/v0.1.0-alpha/lazycommit-0.1.0-alpha-linux_armv6"
      sha256 "926abed893e6b48a873ab2eef17488d15c7911fb9732ba3b965afb928b123e99"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/lazycommit/releases/download/v0.1.0-alpha/lazycommit-0.1.0-alpha-linux_arm64"
      sha256 "16be9bb1c04740306b8b9c2fff68f3061f2fa6496d7847dcba687411020858e3"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
  end

  head do
    url "https://github.com/evilmarty/lazycommit.git", branch: "main"
    depends_on "go" => :build
  end

  test do
    version_output = shell_output(bin/"lazycommit --version")
    assert_match "lazycommit version #{version}", version_output
  end
end
