# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lazycommit < Formula
  desc "Automates generating a commit message from staged changes in a Git repository using a pluggable LLM provider"
  homepage "https://github.com/evilmarty/lazycommit"
  version "0.2.0"
  license "GPL-3.0-or-later"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/evilmarty/lazycommit/releases/download/v0.2.0/lazycommit-0.2.0-darwin_amd64"
      sha256 "b565a53bf4b6f237fe40fde52660600a8223d8cf5b0aa1e01104ce3e0d587d3a"

      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/evilmarty/lazycommit/releases/download/v0.2.0/lazycommit-0.2.0-darwin_arm64"
      sha256 "8bf5eeaf3683ce4e143facfd62cba3c2dbfcf3864651ef49bf3e22a24d0dbd7d"

      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/lazycommit/releases/download/v0.2.0/lazycommit-0.2.0-linux_amd64"
      sha256 "5655d8445565747118d1656fa3f6b39a6772c554a03f795d745a7a8dfc44cac7"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/lazycommit/releases/download/v0.2.0/lazycommit-0.2.0-linux_armv6"
      sha256 "6b066bfc01935a04df1a980d2a2cc88f2f355a9bfdb37e1ea5b0e9c626353525"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/lazycommit/releases/download/v0.2.0/lazycommit-0.2.0-linux_arm64"
      sha256 "e4f263ba358166c8c09cd70fb91cb519d6618953576421c138f570bd94eadac9"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
  end

  head do
    url "https://github.com/evilmarty/lazycommit.git", branch: "main"
    depends_on "go" => :build
  end

  test do
    version_output = shell_output(bin/"lazycommit --version")
    assert_match "lazycommit version #{version}", version_output
  end
end
