# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Spit < Formula
  desc "spit is a Go CLI that sends prompts to OpenAI-compatible chat-completions APIs and streams output."
  homepage "https://github.com/evilmarty/spit"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/evilmarty/spit/releases/download/v0.1.0/spit-0.1.0-darwin_amd64"
      sha256 "5ac799422ccd747db99099b4b5e9a0747532750f22c269c2c0077584210806de"

      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/evilmarty/spit/releases/download/v0.1.0/spit-0.1.0-darwin_arm64"
      sha256 "f31e5c5fdff58517381c51230c0ae2e704353af8f9d0b68cc1fb1cf3d61789a0"

      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/spit/releases/download/v0.1.0/spit-0.1.0-linux_amd64"
      sha256 "6f0db96ddedfe8b2d41a4787d12e8c0a5134222be3fcd1da0033d360a6da55ee"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/spit/releases/download/v0.1.0/spit-0.1.0-linux_armv6"
      sha256 "373a1e84d641231caee0ca607fe75d9f1a627200c8a4f01aa132b0617cd2eb79"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/evilmarty/spit/releases/download/v0.1.0/spit-0.1.0-linux_arm64"
      sha256 "a73879ce55040e47d676e11c3847d56aa3ae3bc58161b4e85bd1068198a54662"
      define_method(:install) do
        if head?
          ldflags = %W[
            -s -w -X main.BuildDate=#{time.iso8601} -X main.Version=#{version} -X main.Commit=#{Utils.git_head}
          ]
          system "go", "build", *std_go_args(ldflags:)
        else
          bin.install Dir["#{name}-*"].first => name
        end
      end
    end
  end

  head do
    url "https://github.com/evilmarty/spit.git", branch: "main"
    depends_on "go" => :build
  end

  test do
    version_output = shell_output(bin/"spit --version")
    assert_match "spit version #{version}", version_output
  end
end
